# Generated by Django 5.2.7 on 2025-10-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['dia_semana', 'hora_inicio']},
        ),
    ]
