# Generated by Django 5.2.7 on 2025-10-14 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_ciudad_paciente_domicilio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pacientes.paciente')),
                ('personales', models.TextField(blank=True, help_text='Antecedentes médicos personales', null=True)),
                ('familiares', models.TextField(blank=True, help_text='Antecedentes médicos familiares', null=True)),
                ('quirurgicos', models.TextField(blank=True, help_text='Cirugías previas', null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, help_text='Medicamentos que toma actualmente', null=True)),
            ],
        ),
    ]
