# Generated by Django 5.2.7 on 2025-10-14 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_antecedente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploracionFisica',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pacientes.paciente')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, help_text='Talla en metros', max_digits=5, null=True)),
                ('presion_arterial', models.CharField(blank=True, help_text='Ej: 120/80', max_length=20, null=True)),
                ('frecuencia_cardiaca', models.PositiveIntegerField(blank=True, help_text='Pulsaciones por minuto', null=True)),
                ('frecuencia_respiratoria', models.PositiveIntegerField(blank=True, help_text='Respiraciones por minuto', null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura en °C', max_digits=4, null=True)),
                ('hallazgos', models.TextField(blank=True, help_text='Hallazgos relevantes en la exploración', null=True)),
            ],
        ),
    ]
